# Generated by Django 4.1.2 on 2022-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critical Priority'), ('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority'), ('TRIVIAL', 'High Priority')], default='HIGH', max_length=50),
            preserve_default=False,
        ),
    ]
