# Generated by Django 4.1.2 on 2022-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('1', 'Critical Priority'), ('2', 'High Priority'), ('3', 'Medium Priority'), ('4', 'Low Priority')], max_length=50),
        ),
    ]
